website/music/urls.py
from django.urls import path
from . import views

# namespace 
app_name = 'music'

urlpatterns = [
    # /music/
    path('', views.IndexView.as_view(), name='index'),

    # /music/<album_id>/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    # /music/<album_id>/favorite/
    # path('<int:album_id>/favorite/', views.favorite, name="favorite"),

    # /music/album/add/
    path('album/add/', views.AlbumCreate.as_view(), name='album-add'),

    # /music/album/2/     update
    path('album/<int:pk>/', views.AlbumUpdate.as_view(), name='album-update'),

    # /music/album/2/     delete
    path('album/<int:pk>/delete/', views.AlbumDelete.as_view(), name='album-delete'),

    # register
    path('register/', views.UserFormView.as_view(), name='register')
 ]

website/website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
]

if settings.DEBUG: 
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

website/music/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
'''
 3 steps to install the update
 python3 manage.py makemigrations music
 python3 manage.py sqlmigrate music 0001
 python3 manage.py migrate
 activate shell python3 manage.py shell
 get all: Album.objects.all()  [running in shell]
 after add filed remember to xx.save()
'''



class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()
    
    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist


''' add song 
 #1 album1.song_set.create(song_title='lucky', file_type='mp3')
 #2
     song = Song()
     song.album = album1
     song.file_type = 'mp3'
     song.song_title = 'i hate my boyfriend'
     song.save()
     Song.objects.all() 
'''
class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title
        
    

website/music/views.py
from django.views import generic
from .models import Album
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
# use generic way
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .form import UserForm


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'album_list'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView): 
    model = Album
    success_url = reverse_lazy('music:index')

class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})


    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            
            user = form.save(commit=False)

            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user.set_password(password)
            user.save()
            
            # returns User objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})      
            

website/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %} Add a new Album {% endblock %}
{% block albums_active %} active {% endblock %}

{% block body %} 
<div class="containe.r-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel-body">
                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data"> 
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/music/templates/music/base.html
<!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Music{% endblock %}</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    </head>

    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <!-- Header -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'music:index' %}"> music </a>
                </div>

                <!-- item -->
                <div class="collpase navbar-collapse" id="topNavBar">
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <a href="{% url 'music:index' %}">
                                <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                            </a>
                        </li>
                        <li class="">
                            <a href="#">
                                <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                            </a>
                        </li>
                    </ul>
                    <form class="navbar-form navbar-left" role="search" method="get" action="#">
                        <div class="form-group">
                            <input type="text" class="form-control" name="q" value="" />
                        </div>
                        <button type="submit" class="btn btn-default">
                            Search
                        </button>
                    </form>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href={% url 'music:album-add' %}>
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                            </a>
                        </li>
                        <li class="">
                            <a href="#">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block body %} 
        
        {% endblock %}
    </body>

    </html>

website/music/templates/music/detail.html
{% extends 'music/base.html' %} {% block title%} {{album}} {% endblock %} {% block body%}
<div class="container-fluid songs-container">
    <div class="row">
        <!-- left album info-->

        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                        <img src="{{ album.album_logo.url }}" class="img-responsive"> {% else %}
                        <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.title }}
                        <small> {{album.genre }}</small>
                    </h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>


        <!-- Right Song info -->
        <div class="col-sm-8 col-md-9">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active">
                    <a href="{% url 'music:detail' album.id %}">View all</a>
                </li>
                <li role="presentation">
                    <a href="#">Add New Song</a>
                </li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>All Songs</h3>
                    {% if error_message %}
                    <p>
                        <strong>{{error_message}}</strong>
                    </p>
                    {% endif %}

                    <table class="table">
                        <thread>
                            <tr>
                                <th>Title</th>
                                <th>Audio File</th>
                                <th>Favorite</th>
                                <th>Actions</th>
                            </tr>
                        </thread>
                        <tbody>
                            {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="#">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>

                                <td>
                                    <a href="#" class="btn-favorite">
                                        <span class="glyphicon glyphicon-star {% if song.is_favorite%}active{% endif%}"></span>
                                    </a>
                                </td>

                                <td>
                                    <form action="#" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/music/templates/music/form-template.html
{% for field in form %} 
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">
            {{ field }}
        </div>
    </div>
{% endfor %}

website/music/templates/music/index.html
{% extends 'music/base.html' %} {% block body %}
<div class="albums-container container-fluid">
    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>My Albums</h3>
        </div>
            {% if album_list %}
            {% for album in album_list %}
            <div class="col-sm-4 col-lg-2">
                <div class="thumbnail">

                    <a href="{% url 'music:detail' album.id %}">
                        <img src="{{ album.album_logo.url }}" class="img-responsive">
                    </a>

                    <div class="caption">
                        <h2>{{ album.album_title }}</h2>
                        <h4>{{ album.artist }}</h4>

                        <!--view details-->
                        <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                        <!-- Delete Album -->
                        <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline">
                            {% csrf_token %}
                            <input type="hidden" name="album_id" value="{{album.id}}" />
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </form>

                        <!--Favorite Album-->
                        <a href="#" class="btn btn-default btn-sm btn-favorite" role="button">
                            <span class="glyphicon glyphicon-star"></span>
                        </a>
                    </div>
                </div>
            </div>
            {% cycle '' '' '' '' '' '<div class="clearfix visible-lg">' %} 
                {% endfor %} 
                {% else %}
                <div class="col-sm-12">
                    <br>
                    <a href="#">
                        <button type="button" class="btn btn-success">
                            <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                        </button>
                    </a>
                </div>
                {% endif %}
            </div>
        </div>
    
    {% endblock %}

website/music/templates/music/old/detail.html
<!--{% extends 'music/base.html' %}
{% block title %} Album Details {% endblock %}
{% block body%}
<img src="{{ album.album_logo }}">
<h1>{{album.album_title}}</h1>
<h3>{{album.artist}}</h1>
<ul>
    {% for song in album.song_set.all %}
        <li> {{song.song_title}} - {{song.file_type}}</li>
    {% endfor%}
</ul-->
<!--
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif%}

<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" />
        <label for="song{{ forloop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="http://i.imgur.com/b9b13Rd.png">
            {% endif%}
        </label><br>
    {% endfor %}
    <input type="submit" value="Favorite" />
</form>
{% endblock %}
-->

<!-- -->
{% extends 'music/base.html' %}
{% block title %} Album Details {% endblock %}

{% block body %}

    <img src="{{album.album_logo }}" style="width: 250px;">
    <h1>{{album.album_title}}</h1>
    <h2>{{album.artist}}</h2>

    {% for song in album.song_set.all %}
        {{ song.song_title }}
        {% if song.is_favorite %}
            <img src="http://i.imgur.com/b9b13Rd.png">
        {% endif %}
        <br>
    {% endfor%}


{% endblock %}

website/music/templates/music/old/index.html
{% block body%}

<!-- change object_list to album_list>
{% if album_list %}
    <h2>Here are all my albums</h2>
    <ul>
        {% for album in album_list %}
        <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
        {% endfor %}
    </ul>
{% else %} 
    <h2>You don't have any albums</h2>
{% endif %}
{% endblock %}
-->

website/music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %} Register {% endblock %}
{% block albums_active %} active {% endblock %}

{% block body %} 
<div class="containe.r-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel-body">
                <h3>Create a new Account</h3>
                {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                {% endif %}
                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data"> 
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}